/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        surface: "var(--color-surface, #f7f9fb)",
        "surface-dim": "var(--color-surface-dim, #d8dadc)",
        "surface-bright": "var(--color-surface-bright, #f7f9fb)",
        "surface-container-lowest": "var(--color-surface-container-lowest, #ffffff)",
        "surface-container-low": "var(--color-surface-container-low, #f2f4f6)",
        "surface-container": "var(--color-surface-container, #eceef0)",
        "surface-container-high": "var(--color-surface-container-high, #e6e8ea)",
        "surface-container-highest": "var(--color-surface-container-highest, #e0e3e5)",
        "on-surface": "var(--color-on-surface, #191c1e)",
        "on-surface-variant": "var(--color-on-surface-variant, #444651)",
        "inverse-surface": "#2d3133",
        "inverse-on-surface": "#eff1f3",
        outline: "#757682",
        "outline-variant": "#c5c5d3",
        "surface-tint": "#4059aa",
        primary: {
          DEFAULT: "#00236f",
          container: "#1e3a8a",
          fixed: "#dce1ff",
          "fixed-dim": "#b6c4ff",
          dark: "#0a192f",
        },
        "on-primary": "#ffffff",
        "on-primary-container": "#90a8ff",
        "on-primary-fixed": "#00164e",
        "on-primary-fixed-variant": "#264191",
        secondary: {
          DEFAULT: "#0051d5",
          container: "#316bf3",
          fixed: "#dbe1ff",
          "fixed-dim": "#b4c5ff",
        },
        "on-secondary": "#ffffff",
        "on-secondary-container": "#fefcff",
        "on-secondary-fixed": "#00174b",
        "on-secondary-fixed-variant": "#003ea8",
        tertiary: {
          DEFAULT: "#00311f",
          container: "#004a31",
          fixed: "#6ffbbe",
          "fixed-dim": "#4edea3",
        },
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#27c38a",
        "on-tertiary-fixed": "#002113",
        "on-tertiary-fixed-variant": "#005236",
        background: "var(--color-background, #f7f9fb)",
        "on-background": "var(--color-on-background, #191c1e)",
        "slate-text": "#1E293B",
        "slate-muted": "#64748B",
        "border-light": "var(--color-border-light, #E2E8F0)",
        "status-success": "#059669",
        "status-warning": "#F59E0B",
        "status-error": "#DC2626",
        error: "#ba1a1a",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
        display: ['Public Sans', 'Inter', 'system-ui', 'sans-serif'],
        mono: ['JetBrains Mono', 'Menlo', 'monospace'],
      },
      boxShadow: {
        subtle: "0 1px 3px 0 rgba(0, 0, 0, 0.05), 0 1px 2px -1px rgba(0, 0, 0, 0.05)",
        card: "0 4px 6px -1px rgba(0, 0, 0, 0.04), 0 2px 4px -2px rgba(0, 0, 0, 0.04)",
        elevated: "0 10px 15px -3px rgba(0, 0, 0, 0.08), 0 4px 6px -4px rgba(0, 0, 0, 0.04)",
        glow: "0 0 20px -5px rgba(0, 81, 213, 0.3)",
      },
      borderRadius: {
        'gov': '0.375rem',
      }
    },
  },
  plugins: [],
}
