import React, { createContext, useContext, useState, useEffect } from 'react';
import { Language } from '../types';

export interface LanguageOption {
  code: Language;
  name: string;
  nativeName: string;
}

export const LANGUAGES: LanguageOption[] = [
  { code: 'en', name: 'English', nativeName: 'English' },
  { code: 'hi', name: 'Hindi', nativeName: 'हिन्दी' },
  { code: 'bn', name: 'Bengali', nativeName: 'বাংলা' },
  { code: 'ta', name: 'Tamil', nativeName: 'தமிழ்' },
  { code: 'te', name: 'Telugu', nativeName: 'తెలుగు' },
  { code: 'mr', name: 'Marathi', nativeName: 'मराठी' },
  { code: 'gu', name: 'Gujarati', nativeName: 'ગુજરાતી' },
  { code: 'kn', name: 'Kannada', nativeName: 'ಕನ್ನಡ' },
];

export const TRANSLATIONS: Record<Language, Record<string, string>> = {
  en: {
    appTitle: 'JanSetu AI',
    initiativeBadge: 'Digital Public Infrastructure Initiative',
    searchPlaceholder: 'Ask about any scheme, submit a civic grievance, or simplify an official circular...',
    heroQuestion: 'How can we assist you today?',
    heroTagline: 'Empowering 1.4 Billion Citizens with AI-Driven Public Governance',
    analyzeBtn: 'Analyze with AI',
    findSchemes: 'Find Welfare Schemes',
    trackGrievance: 'Track Grievances',
    analyzeDoc: 'Simplify Circulars',
    rtiAssistant: 'RTI Drafter',
    digilockerVault: 'DigiLocker Vault',
    dashboard: 'Dashboard',
    schemes: 'Welfare Schemes',
    grievances: 'Grievances',
    documents: 'Document Vault',
    helpdesk: 'Toll-Free Helpdesk',
    accessibility: 'Accessibility',
    citizenProfile: 'Citizen Profile',
    highContrast: 'High Contrast',
    darkMode: 'Dark Mode',
    lightMode: 'Light Mode',
    textSize: 'Text Size',
    smartGrievanceTitle: 'Smart Grievance Logging',
    smartGrievanceSubtitle: 'Upload a photo, type, or speak your issue. AI will auto-triage to the right department.',
    dragDropText: 'Drag & drop photos or complaints here',
    dragDropSub: 'JPEG, PNG, WebP up to 10MB',
    or: 'OR',
    typeGrievancePlaceholder: 'Type your grievance (e.g. Broken water pipe at Shivaji Nagar)...',
    analyzingWithGemini: 'Analyzing & Routing with AI...',
    aiRoutingPreview: 'AI Auto-Routing Preview',
    citizenCopilotTitle: 'Citizen Co-Pilot',
    personalizedMatches: 'Personalized scheme matches',
    activeProfile: 'Active Profile',
    applyWithCopilot: 'Apply with AI Co-Pilot',
    documentSimplifierTitle: 'Official Document Simplifier',
    originalDocument: 'Original Document',
    aiSimplifiedSummary: 'AI Simplified Summary',
    coreObjective: 'Core Objective',
    eligibilityCriteria: 'Eligibility Criteria',
    keyDeadline: 'Key Deadline',
    translateTo: 'Translate',
    listen: 'Listen',
    liveIntelligence: 'Live Platform Intelligence',
    totalResolved: 'Total Grievances Resolved',
    aiAccuracy: 'AI Accuracy Rate',
    schemesIndexed: 'Indexed DPI Schemes',
    avgResolution: 'Average Resolution Time',
    recentActivity: 'Live Governance Activity Feed',
    apiKeyConfig: 'AI API Key',
    apiKeyActive: 'Connected to AI Engine',
  },
  hi: {
    appTitle: 'जनसेतु AI',
    initiativeBadge: 'डिजिटल पब्लिक इंफ्रास्ट्रक्चर पहल',
    searchPlaceholder: 'किसी भी सरकारी योजना के बारे में पूछें, नागरिक शिकायत दर्ज करें...',
    heroQuestion: 'आज हम आपकी क्या सहायता कर सकते हैं?',
    heroTagline: 'एआई-संचालित जन शासन के साथ 140 करोड़ नागरिकों का सशक्तिकरण',
    analyzeBtn: 'एआई से विश्लेषण करें',
    findSchemes: 'कल्याणकारी योजनाएं खोजें',
    trackGrievance: 'शिकायत ट्रैक करें',
    analyzeDoc: 'सरकारी परिपत्र समझें',
    rtiAssistant: 'आरटीआई सहायक',
    digilockerVault: 'डिजिलॉकर वॉल्ट',
    dashboard: 'डैशबोर्ड',
    schemes: 'सरकारी योजनाएं',
    grievances: 'नागरिक शिकायतें',
    documents: 'दस्तावेज़ वॉल्ट',
    helpdesk: 'टोल-फ्री हेल्पलाइन',
    accessibility: 'सुगम्यता (Accessibility)',
    citizenProfile: 'नागरिक प्रोफाइल',
    highContrast: 'हाई कंट्रास्ट',
    darkMode: 'डार्क मोड',
    lightMode: 'लाइट मोड',
    textSize: 'टेक्स्ट आकार',
    smartGrievanceTitle: 'स्मार्ट शिकायत निवारण',
    smartGrievanceSubtitle: 'तस्वीर अपलोड करें, लिखें या बोलें। एआई सही विभाग को स्वचालित रूप से असाइन करेगा।',
    dragDropText: 'फोटो या शिकायत पत्र यहाँ खींचकर छोड़ें',
    dragDropSub: 'JPEG, PNG, WebP (10MB तक)',
    or: 'या',
    typeGrievancePlaceholder: 'अपनी शिकायत यहाँ लिखें (जैसे: मुख्य सड़क पर बड़ा गड्ढा)...',
    analyzingWithGemini: 'एआई द्वारा विश्लेषण व रूटिंग जारी...',
    aiRoutingPreview: 'एआई ऑटो-रूटिंग पूर्वावलोकन',
    citizenCopilotTitle: 'नागरिक को-पायलट',
    personalizedMatches: 'आपके लिए चयनित सरकारी योजनाएं',
    activeProfile: 'सक्रिय प्रोफाइल',
    applyWithCopilot: 'एआई को-पायलट से आवेदन करें',
    documentSimplifierTitle: 'सरकारी परिपत्र सरलीकरण',
    originalDocument: 'मूल दस्तावेज़',
    aiSimplifiedSummary: 'एआई सरल सारांश',
    coreObjective: 'मुख्य उद्देश्य',
    eligibilityCriteria: 'पात्रता मानदंड',
    keyDeadline: 'अंतिम तिथि / समयसीमा',
    translateTo: 'अनुवाद करें',
    listen: 'ऑडियो सुनें',
    liveIntelligence: 'लाइव गवर्नेंस इंटेलिजेंस',
    totalResolved: 'कुल निवारित शिकायतें',
    aiAccuracy: 'एआई सटीकता दर',
    schemesIndexed: 'सूचीबद्ध योजनाएं',
    avgResolution: 'औसत समाधान समय',
    recentActivity: 'लाइव प्रशासनिक गतिविधि',
    apiKeyConfig: 'जेमिनी एपीआई कुंजी',
    apiKeyActive: 'जेमिनी एपीआई से कनेक्टेड',
  },
  bn: {
    appTitle: 'জনসেতু AI',
    initiativeBadge: 'ডিজিটাল পাবলিক ইনফ্রাস্ট্রাকচার উদ্যোগ',
    searchPlaceholder: 'যেকোনো সরকারি স্কিম সম্পর্কে জিজ্ঞাসা করুন বা অভিযোগ নথিভুক্ত করুন...',
    heroQuestion: 'আজ আমরা কীভাবে আপনাকে সাহায্য করতে পারি?',
    heroTagline: 'এআই-চালিত শাসনের মাধ্যমে নাগরিকদের ক্ষমতায়ন',
    analyzeBtn: 'বিশ্লেষণ করুন',
    findSchemes: 'সরকারি স্কিম খুঁজুন',
    trackGrievance: 'অভিযোগ ট্র্যাক করুন',
    analyzeDoc: 'পরিপত্র সরলীকরণ',
    rtiAssistant: 'আরটিআই ড্রাফটার',
    digilockerVault: 'ডিজিলকার ভল্ট',
    dashboard: 'ড্যাশবোর্ড',
    schemes: 'কল্যাণমূলক স্কিম',
    grievances: 'নাগরিক অভিযোগ',
    documents: 'নথিপত্র ভল্ট',
    helpdesk: 'টোল-ফ্রি হেল্পডেস্ক',
    accessibility: 'অ্যাক্সেসিবিলিটি',
    citizenProfile: 'নাগরিক প্রোফাইল',
    highContrast: 'হাই কন্ট্রাস্ট',
    darkMode: 'ডার্ক মোড',
    lightMode: 'লাইট মোড',
    textSize: 'টেক্সট সাইজ',
    smartGrievanceTitle: 'স্মার্ট অভিযোগ পোর্টাল',
    smartGrievanceSubtitle: 'ছবি আপলোড করুন বা কণ্ঠস্বর রেকর্ড করুন।',
    dragDropText: 'ফটো বা অভিযোগ নথি এখানে ড্রপ করুন',
    dragDropSub: 'JPEG, PNG, WebP (১০ এমবি পর্যন্ত)',
    or: 'অথবা',
    typeGrievancePlaceholder: 'আপনার অভিযোগ এখানে লিখুন...',
    analyzingWithGemini: 'এআই বিশ্লেষণ চলছে...',
    aiRoutingPreview: 'এআই অটো-রাউটিং প্রিভিউ',
    citizenCopilotTitle: 'নাগরিক কো-পাইলট',
    personalizedMatches: 'ব্যক্তিগত স্কিম ম্যাচ',
    activeProfile: 'সক্রিয় প্রোফাইল',
    applyWithCopilot: 'সহজে আবেদন করুন',
    documentSimplifierTitle: 'সরকারি নথি সরলীকরণ',
    originalDocument: 'মূল নথি',
    aiSimplifiedSummary: 'সহজ বাংলা সারাংশ',
    coreObjective: 'মূল উদ্দেশ্য',
    eligibilityCriteria: 'যোগ্যতার মাপকাঠি',
    keyDeadline: 'সময়সীমা',
    translateTo: 'অনুবাদ',
    listen: 'শুনুন',
    liveIntelligence: 'লাইভ প্ল্যাটফর্ম ডেটা',
    totalResolved: 'মোট সমাধান করা অভিযোগ',
    aiAccuracy: 'এআই নির্ভুলতা',
    schemesIndexed: 'তালিকাভুক্ত স্কিম',
    avgResolution: 'গড় সমাধানের সময়',
    recentActivity: 'লাইভ অ্যাক্টিভিটি ফিড',
    apiKeyConfig: 'এপিআই কি কনফিগ',
    apiKeyActive: 'সংযুক্ত রয়েছে',
  },
  ta: {
    appTitle: 'ஜனசேது AI',
    initiativeBadge: 'டிஜிட்டல் பொது உள்கட்டமைப்பு முயற்சி',
    searchPlaceholder: 'அரசு நலத்திட்டங்கள் பற்றி கேட்கவும் அல்லது புகார் பதிவு செய்யவும்...',
    heroQuestion: 'இன்று நாங்கள் உங்களுக்கு எவ்வாறு உதவலாம்?',
    heroTagline: 'ஏஐ மூலம் குடிமக்கள் சேவை மற்றும் நிர்வாகம்',
    analyzeBtn: 'ஆய்வு செய்',
    findSchemes: 'நலத்திட்டங்கள்',
    trackGrievance: 'புகாரைக் கண்காணிக்கவும்',
    analyzeDoc: 'ஆவண சுருக்கம்',
    rtiAssistant: 'ஆர்டிஐ உதவியாளர்',
    digilockerVault: 'டிஜிலாக்கர் பெட்டகம்',
    dashboard: 'டாஷ்போர்டு',
    schemes: 'நலத்திட்டங்கள்',
    grievances: 'குடிமக்கள் புகார்கள்',
    documents: 'ஆவணங்கள்',
    helpdesk: 'இலவச உதவி எண்',
    accessibility: 'அணுகல்தன்மை',
    citizenProfile: 'குடிமகன் சுயவிவரம்',
    highContrast: 'உயர் மாறுபாடு',
    darkMode: 'இருண்ட பயன்முறை',
    lightMode: 'ஒளி பயன்முறை',
    textSize: 'எழுத்து அளவு',
    smartGrievanceTitle: 'ஸ்மார்ட் குறைதீர்க்கும் தளம்',
    smartGrievanceSubtitle: 'புகைப்படம் அல்லது குரல் மூலம் உங்கள் புகாரை பதிவு செய்யுங்கள்.',
    dragDropText: 'புகைப்படங்களை இங்கே இழுத்து விடவும்',
    dragDropSub: 'JPEG, PNG, WebP (10MB வரை)',
    or: 'அல்லது',
    typeGrievancePlaceholder: 'உங்கள் புகாரை இங்கே தட்டச்சு செய்யவும்...',
    analyzingWithGemini: 'ஏஐ ஆய்வு செய்கிறது...',
    aiRoutingPreview: 'தானியங்கி துறை தேர்வு',
    citizenCopilotTitle: 'குடிமக்கள் வழிகாட்டி',
    personalizedMatches: 'பொருத்தமான திட்டங்கள்',
    activeProfile: 'செயலில் உள்ள விவரம்',
    applyWithCopilot: 'உடனடியாக விண்ணப்பிக்கவும்',
    documentSimplifierTitle: 'அரசு ஆணை சுருக்கம்',
    originalDocument: 'அசல் ஆவணம்',
    aiSimplifiedSummary: 'எளிய தமிழ் விளக்கம்',
    coreObjective: 'முக்கிய நோக்கம்',
    eligibilityCriteria: 'தகுதி வரம்பு',
    keyDeadline: 'கடைசி தேதி',
    translateTo: 'மொழிபெயர்',
    listen: 'கேளுங்கள்',
    liveIntelligence: 'நேரலை புள்ளிவிவரங்கள்',
    totalResolved: 'தீர்க்கப்பட்ட புகார்கள்',
    aiAccuracy: 'ஏஐ துல்லியம்',
    schemesIndexed: 'திட்டங்கள்',
    avgResolution: 'சராசரி தீர்வு நேரம்',
    recentActivity: 'நடப்பு நிகழ்வுகள்',
    apiKeyConfig: 'API சாவி',
    apiKeyActive: 'இணைக்கப்பட்டுள்ளது',
  },
  te: {
    appTitle: 'జనసేతు AI',
    initiativeBadge: 'డిజిటల్ పబ్లిక్ ఇన్‌ఫ్రాస్ట్రక్చర్ చొరవ',
    searchPlaceholder: 'ప్రభుత్వ పథకాలు లేదా ప్రజా సమస్యల గురించి అడగండి...',
    heroQuestion: 'ఈరోజు మేము మీకు ఎలా సహాయపడగలము?',
    heroTagline: 'ఏఐతో పౌర పాలన మరియు సంక్షేమం',
    analyzeBtn: 'విశ్లేషించండి',
    findSchemes: 'సంక్షేమ పథకాలు',
    trackGrievance: 'ఫిర్యాదు ట్రాక్ చేయండి',
    analyzeDoc: 'ఉత్తర్వుల సరళీకరణ',
    rtiAssistant: 'RTI అసిస్టెంట్',
    digilockerVault: 'డిజిలాకర్ వాల్ట్',
    dashboard: 'డ్యాష్‌బోర్డ్',
    schemes: 'పథకాలు',
    grievances: 'ఫిర్యాదులు',
    documents: 'పత్రాలు',
    helpdesk: 'టోల్-ఫ్రీ హెల్ప్‌లైన్',
    accessibility: 'సౌలభ్యం',
    citizenProfile: 'పౌర ప్రొఫైల్',
    highContrast: 'హై కాంట్రాస్ట్',
    darkMode: 'డార్క్ మోడ్',
    lightMode: 'లైట్ మోడ్',
    textSize: 'అక్షర పరిమాణం',
    smartGrievanceTitle: 'స్మార్ట్ గ్రీవెన్స్ పోర్టల్',
    smartGrievanceSubtitle: 'ఫోటో లేదా వాయిస్ ద్వారా సమస్యను సులభంగా నమోదు చేయండి.',
    dragDropText: 'ఫోటోలను ఇక్కడ డ్రాప్ చేయండి',
    dragDropSub: 'JPEG, PNG, WebP (10MB వరకు)',
    or: 'లేదా',
    typeGrievancePlaceholder: 'మీ సమస్యను ఇక్కడ టైప్ చేయండి...',
    analyzingWithGemini: 'విశ్లేషిస్తోంది...',
    aiRoutingPreview: 'ఆటో-రూటింగ్ ప్రివ్యూ',
    citizenCopilotTitle: 'సిటిజన్ కో-పైలట్',
    personalizedMatches: 'మీకు సరిపోయే పథకాలు',
    activeProfile: 'యాక్టివ్ ప్రొఫైల్',
    applyWithCopilot: 'దరఖాస్తు చేసుకోండి',
    documentSimplifierTitle: 'ప్రభుత్వ పత్రాల వివరణ',
    originalDocument: 'అసలు పత్రం',
    aiSimplifiedSummary: 'సరళమైన తెలుగు సారాంశం',
    coreObjective: 'ప్రధాన లక్ష్యం',
    eligibilityCriteria: 'అర్హతలు',
    keyDeadline: 'చివరి గడువు',
    translateTo: 'అనువాదం',
    listen: 'వినండి',
    liveIntelligence: 'లైవ్ సమాచారం',
    totalResolved: 'పరిష్కరించబడినవి',
    aiAccuracy: 'ఖచ్చితత్వం',
    schemesIndexed: 'పథకాలు',
    avgResolution: 'సగటు సమయం',
    recentActivity: 'తాజా పురోగతి',
    apiKeyConfig: 'API కీ',
    apiKeyActive: 'కనెక్ట్ అయింది',
  },
  mr: {
    appTitle: 'जनसेतू AI',
    initiativeBadge: 'डिजिटल पब्लिक इन्फ्रास्ट्रक्चर पुढाकार',
    searchPlaceholder: 'कोणत्याही सरकारी योजनेबद्दल विचारा किंवा नागरी तक्रार नोंदवा...',
    heroQuestion: 'आज आम्ही तुम्हाला कशी मदत करू शकतो?',
    heroTagline: 'एआय-सक्षम प्रशासनाद्वारे नागरिकांचे सबलीकरण',
    analyzeBtn: 'विश्लेषण करा',
    findSchemes: 'कल्याणकारी योजना',
    trackGrievance: 'तक्रार ट्रॅक करा',
    analyzeDoc: 'सरकारी परिपत्रक सुलभ करा',
    rtiAssistant: 'माहिती अधिकार (RTI)',
    digilockerVault: 'डिजीलॉकर व्हॉल्ट',
    dashboard: 'डॅशबोर्ड',
    schemes: 'योजना',
    grievances: 'तक्रारी',
    documents: 'कागदपत्रे',
    helpdesk: 'टोल-फ्री हेल्पलाईन',
    accessibility: 'सुगमता',
    citizenProfile: 'नागरिक प्रोफाइल',
    highContrast: 'हाय कॉन्ट्रास्ट',
    darkMode: 'डार्क मोड',
    lightMode: 'लाईट मोड',
    textSize: 'मजकूर आकार',
    smartGrievanceTitle: 'स्मार्ट तक्रार निवारण',
    smartGrievanceSubtitle: 'फोटो अपलोड करा, लिहा किंवा बोला. संबंधित विभागाकडे थेट पाठवले जाईल.',
    dragDropText: 'फोटो किंवा तक्रार अर्ज येथे टाका',
    dragDropSub: 'JPEG, PNG, WebP (10MB पर्यंत)',
    or: 'किंवा',
    typeGrievancePlaceholder: 'आपली तक्रार येथे लिहा...',
    analyzingWithGemini: 'एआय विश्लेषण चालू आहे...',
    aiRoutingPreview: 'ऑटो-राउटिंग पूर्वावलोकन',
    citizenCopilotTitle: 'नागरिक सह-पायलट',
    personalizedMatches: 'आपल्यासाठी पात्र योजना',
    activeProfile: 'सक्रिय प्रोफाइल',
    applyWithCopilot: 'सहज अर्ज करा',
    documentSimplifierTitle: 'परिपत्रक सरलीकरण',
    originalDocument: 'मूळ दस्तऐवज',
    aiSimplifiedSummary: 'सोप्या मराठीत सारांश',
    coreObjective: 'मुख्य उद्दिष्ट',
    eligibilityCriteria: 'पात्रता निकष',
    keyDeadline: 'अंतिम मुदत',
    translateTo: 'भाषांतर करा',
    listen: 'ऐका',
    liveIntelligence: 'थेट आकडेवारी',
    totalResolved: 'एकूण निवारण',
    aiAccuracy: 'अचूकता दर',
    schemesIndexed: 'नोंदणीकृत योजना',
    avgResolution: 'सरासरी वेळ',
    recentActivity: 'थेट प्रशासकीय घडामोडी',
    apiKeyConfig: 'API की',
    apiKeyActive: 'कनेक्टेड आहे',
  },
  gu: {
    appTitle: 'જનસેતુ AI',
    initiativeBadge: 'ડિજિટલ પબ્લિક ઇન્ફ્રાસ્ટ્રક્ચર પહેલ',
    searchPlaceholder: 'કોઈપણ સરકારી યોજના વિશે પૂછો અથવા ફરિયાદ નોંધાવો...',
    heroQuestion: 'આજે અમે તમને કેવી રીતે મદદ કરી શકીએ?',
    heroTagline: 'એઆઈ દ્વારા પારદર્શક નાગરિક શાસન',
    analyzeBtn: 'વિશ્લેષણ કરો',
    findSchemes: 'સરકારી યોજનાઓ',
    trackGrievance: 'ફરિયાદ ટ્રેક કરો',
    analyzeDoc: 'પરિપત્ર સરળ બનાવો',
    rtiAssistant: 'RTI સહાયક',
    digilockerVault: 'ડિજીલોકર વૉલ્ટ',
    dashboard: 'ડેશબોર્ડ',
    schemes: 'યોજનાઓ',
    grievances: 'ફરિયાદો',
    documents: 'દસ્તાવેજો',
    helpdesk: 'હેલ્પલાઇન',
    accessibility: 'એક્સેસિબિલિટી',
    citizenProfile: 'નાગરિક પ્રોફાઇલ',
    highContrast: 'હાઇ કોન્ટ્રાસ્ટ',
    darkMode: 'ડાર્ક મોડ',
    lightMode: 'લાઇટ મોડ',
    textSize: 'અક્ષર માપ',
    smartGrievanceTitle: 'સ્માર્ટ ફરિયાદ નિવારણ',
    smartGrievanceSubtitle: 'ફોટો અપલોડ કરો અથવા બોલીને ફરિયાદ નોંધાવો.',
    dragDropText: 'ફોટો અહીં ડ્રોપ કરો',
    dragDropSub: 'JPEG, PNG, WebP (10MB સુધી)',
    or: 'અથવા',
    typeGrievancePlaceholder: 'તમારી ફરિયાદ અહીં લખો...',
    analyzingWithGemini: 'વિશ્લેષણ થઈ રહ્યું છે...',
    aiRoutingPreview: 'ઓટો-રાઉટિંગ પૂર્વાવલોકન',
    citizenCopilotTitle: 'સિટિઝન કો-પાઇલટ',
    personalizedMatches: 'તમારા માટે યોગ્ય યોજનાઓ',
    activeProfile: 'સક્રિય પ્રોફાઇલ',
    applyWithCopilot: 'સરળતાથી અરજી કરો',
    documentSimplifierTitle: 'સરકારી પરિપત્ર સરળીકરણ',
    originalDocument: 'મૂળ દસ્તાવેજ',
    aiSimplifiedSummary: 'સરળ ગુજરાતી સારાંશ',
    coreObjective: 'મુખ્ય ઉદ્દેશ',
    eligibilityCriteria: 'પાત્રતા માપદંડ',
    keyDeadline: 'છેલ્લી તારીખ',
    translateTo: 'અનુવાદ',
    listen: 'સાંભળો',
    liveIntelligence: 'લાઈવ માહિતી',
    totalResolved: 'ઉકેલાયેલી ફરિયાદો',
    aiAccuracy: 'ચોકસાઈ દર',
    schemesIndexed: 'યોજનાઓ',
    avgResolution: 'સરેરાશ સમય',
    recentActivity: 'તાજી પ્રવૃત્તિ',
    apiKeyConfig: 'API કી',
    apiKeyActive: 'જોડાયેલ છે',
  },
  kn: {
    appTitle: 'ಜನಸೇತು AI',
    initiativeBadge: 'ಡಿಜಿಟಲ್ ಸಾರ್ವಜನಿಕ ಮೂಲಸೌಕರ್ಯ ಉಪಕ್ರಮ',
    searchPlaceholder: 'ಯಾವುದೇ ಸರ್ಕಾರಿ ಯೋಜನೆಗಳ ಬಗ್ಗೆ ಕೇಳಿ ಅಥವಾ ದೂರು ಸಲ್ಲಿಸಿ...',
    heroQuestion: 'ಇಂದು ನಾವು ನಿಮಗೆ ಹೇಗೆ ಸಹಾಯ ಮಾಡಬಹುದು?',
    heroTagline: 'ಎಐ ಮೂಲಕ ಪಾರದರ್ಶಕ ನಾಗರಿಕ ಸೇವೆ',
    analyzeBtn: 'ವಿಶ್ಲೇಷಿಸಿ',
    findSchemes: 'ಯೋಜನೆಗಳು',
    trackGrievance: 'ದೂರು ಟ್ರ್ಯಾಕ್ ಮಾಡಿ',
    analyzeDoc: 'ದಾಖಲೆ ಸರಳೀಕರಣ',
    rtiAssistant: 'ಆರ್‌ಟಿಐ ಸಹಾಯಕ',
    digilockerVault: 'ಡಿಜಿಲಾಕರ್ ವಾಲ್ಟ್',
    dashboard: 'ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
    schemes: 'ಯೋಜನೆಗಳು',
    grievances: 'ದೂರುಗಳು',
    documents: 'ದಾಖಲೆಗಳು',
    helpdesk: 'ಉಚಿತ ಸಹಾಯವಾಣಿ',
    accessibility: 'ಪ್ರವೇಶಿಸುವಿಕೆ',
    citizenProfile: 'ನಾಗರಿಕ ವಿವರ',
    highContrast: 'ಹೈ ಕಾಂಟ್ರಾಸ್ಟ್',
    darkMode: 'ಡಾರ್ಕ್ ಮೋಡ್',
    lightMode: 'ಲೈಟ್ ಮೋಡ್',
    textSize: 'ಪಠ್ಯ ಗಾತ್ರ',
    smartGrievanceTitle: 'ಸ್ಮಾರ್ಟ್ ಕುಂದುಕೊರತೆ ಪೋರ್ಟಲ್',
    smartGrievanceSubtitle: 'ಫೋಟೋ ಅಪ್‌ಲೋಡ್ ಮಾಡಿ ಅಥವಾ ಧ್ವನಿ ಮೂಲಕ ದೂರು ನೀಡಿ.',
    dragDropText: 'ಫೋಟೋಗಳನ್ನು ಇಲ್ಲಿ ಬಿಡಿ',
    dragDropSub: 'JPEG, PNG, WebP (10MB ವರೆಗೆ)',
    or: 'ಅಥವಾ',
    typeGrievancePlaceholder: 'ನಿಮ್ಮ ದೂರನ್ನು ಇಲ್ಲಿ ಬರೆಯಿರಿ...',
    analyzingWithGemini: 'ವಿಶ್ಲೇಷಿಸಲಾಗುತ್ತಿದೆ...',
    aiRoutingPreview: 'ವಿಭಾಗ ನಿಯೋಜನೆ',
    citizenCopilotTitle: 'ಸಿಟಿಜನ್ ಕೋ-ಪೈಲಟ್',
    personalizedMatches: 'ನಿಮಗಾಗಿ ಸೂಕ್ತ ಯೋಜನೆಗಳು',
    activeProfile: 'ಸಕ್ರಿಯ ವಿವರ',
    applyWithCopilot: 'ಅರ್ಜಿ ಸಲ್ಲಿಸಿ',
    documentSimplifierTitle: 'ಸರ್ಕಾರಿ ಸುತ್ತೋಲೆ ವಿವರಣೆ',
    originalDocument: 'ಮೂಲ ದಾಖಲೆ',
    aiSimplifiedSummary: 'ಸರಳ ಕನ್ನಡ ಸಾರಾಂಶ',
    coreObjective: 'ಮುಖ್ಯ ಉದ್ದೇಶ',
    eligibilityCriteria: 'ಅರ್ಹತೆಯ ಮಾನದಂಡ',
    keyDeadline: 'ಕೊನೆಯ ದಿನಾಂಕ',
    translateTo: 'ಅನುವಾದಿಸಿ',
    listen: 'ಕೇಳಿ',
    liveIntelligence: 'ಲೈವ್ ಅಂಕಿಅಂಶ',
    totalResolved: 'ಪರಿಹರಿಸಲಾದ ದೂರುಗಳು',
    aiAccuracy: 'ನಿಖರತೆ',
    schemesIndexed: 'ಯೋಜನೆಗಳು',
    avgResolution: 'ಸರಾಸರಿ ಸಮಯ',
    recentActivity: 'ಇತ್ತೀಚಿನ ಪ್ರಗತಿ',
    apiKeyConfig: 'API ಕೀ',
    apiKeyActive: 'ಸಂಪರ್ಕಗೊಂಡಿದೆ',
  }
};

interface LanguageContextType {
  currentLanguage: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  languages: LanguageOption[];
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [currentLanguage, setCurrentLanguage] = useState<Language>(() => {
    const saved = localStorage.getItem('jansetu_language') as Language;
    return saved && TRANSLATIONS[saved] ? saved : 'en';
  });

  const setLanguage = (lang: Language) => {
    setCurrentLanguage(lang);
    localStorage.setItem('jansetu_language', lang);
  };

  const t = (key: string): string => {
    return TRANSLATIONS[currentLanguage]?.[key] || TRANSLATIONS.en?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ currentLanguage, setLanguage, t, languages: LANGUAGES }}>
      {children}
    </LanguageContext.Provider>
  );
};

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
